all:
  hosts:
    server:
      ansible_host: 192.168.29.150
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
    client:
      ansible_host: 192.168.29.151
      ansible_port: 22
      ansible_user: vagrant
      ansible_password: vagrant
